ARG PY_VERSION="3.5"
ARG DIST="slim"

FROM python:${PY_VERSION}-${DIST}

WORKDIR /cartpole-rl-remote

COPY requirement*.txt ./

RUN pip install -U pip && \
    pip install -r requirements.txt -r requirements-dev.txt && \
    rm -rf /root/.cache

ADD . .
