version: '3.3'
services:

  mongo:
    image: mongo:3.6
    networks:
      default:
        aliases:
          - mongo
    ports:
      - "27017:27017"

  backend:
    depends_on:
      - mongo
    links:
      - mongo
    image: engapa/modeldb-backend:latest
    networks:
      default:
        aliases:
          - backend
    ports:
      - "6543:6543"
    command: ["mongo"]

  frontend:
    depends_on:
      - backend
      - mongo
    links:
      - backend
    environment:
      - MDB_BACKEND_HOST=backend
    image: engapa/modeldb-frontend:latest
    networks:
      default:
        aliases:
          - frontend
    ports:
      - "3000:3000"

  cartpole:
    depends_on:
      - frontend
    build: ../
    image: hypnosapos/${DOCKER_IMAGE:-cartpole-rl-remote}:${DOCKER_TAG:-latest}
    command: >-
      bash -c "
      until curl --output /dev/null -f --silent --head --fail http://frontend:3000; do
        sleep 5
      done &&
      cartpole -e ${TRAIN_EPISODES:-200}
      --metrics-engine modeldb --metrics-config '{\"syncer_conf\": \"/tmp/modeldb/syncer.json\"}'
      train --gamma 0.095 0.099 0.001 -f /tmp/models/cartpole-rl-remote"
    volumes:
      - ../.models:/tmp/models
      - ../scaffold/modeldb/syncer.json:/tmp/modeldb/syncer.json