apiVersion: v1
kind: PersistentVolume
metadata:
  name: polyaxon-pv-logs
  labels:
    app: polyaxon
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFS_HOST  # Use the right IP
    path: "/data/logs"
  claimRef:
    namespace: polyaxon
    name: polyaxon-pvc-logs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: polyaxon-pvc-logs
  namespace: polyaxon
  labels:
    app: polyaxon
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
